// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAtGWz1ovkS8g50fpjWryaWmGpYcIyp7A',
    appId: '1:292090677184:web:7525a9a413c63517246a25',
    messagingSenderId: '292090677184',
    projectId: 'tik-tok-jegal',
    authDomain: 'tik-tok-jegal.firebaseapp.com',
    storageBucket: 'tik-tok-jegal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx2SS8RLdxvXHZ8C3oUDYjYXKHx7VtY7c',
    appId: '1:292090677184:android:f231e708e696ddd9246a25',
    messagingSenderId: '292090677184',
    projectId: 'tik-tok-jegal',
    storageBucket: 'tik-tok-jegal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA03_gKRxvxo_vBPCt851S3xzGlw1SvyQc',
    appId: '1:292090677184:ios:fa8286a766960bd3246a25',
    messagingSenderId: '292090677184',
    projectId: 'tik-tok-jegal',
    storageBucket: 'tik-tok-jegal.appspot.com',
    iosClientId: '292090677184-fp6rng9fl1peb6oivfqmmfjntqfrev3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
